config/routes.rb
Rails.application.routes.draw do
  # rooms
  root 'rooms#index'
  resources :rooms

  # devise
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :room
  belongs_to :user
  validates :content, presence: true
  after_create_commit { BroadcastNewPostJob.perform_later self }
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :must_be_logged_in, except: [:index]

  include Pagy::Backend

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @pagy, @posts = pagy(@room.posts.order(created_at: :desc), items: 15)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room)
    else
      flash.now.alert = "ルーム作成に失敗しました。"
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      redirect_to room_path(@room)
    else
      flash.now.alert = "ルーム更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def must_be_logged_in
    unless user_signed_in?
      flash.alert = "ログインしてください。"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ActionCableChat
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
  body
    #flash
      - if flash.any?
        - flash.each do |message_type, message|
            = tag.p message
    #account
      - if user_signed_in?
        | You're logged in as:&nbsp;
        = tag.span current_user.email
      - else
        | Not logged in.
    #links
      = link_to "ルーム一覧", root_path
      - if user_signed_in?
        = link_to "ルーム新規作成", new_room_path
        = link_to "ログアウト", destroy_user_session_path,
            method: :delete, data: { confirm: "ログアウトしますか?" }
      - else
        = link_to "新規登録", new_user_registration_path
        = link_to "ログイン", new_user_session_path
    = yield

app/views/posts/_post.html.slim
p.single_post
  = tag.span "#{post.user.email.sub(/@.+\Z/,'')}: #{post.content} "
  = tag.span "[#{post.created_at.strftime('%m/%d %H:%M')}]", class: 'datetime'

app/views/rooms/edit.html.slim
h1 Rooms#edit

= form_with(model: @room, local: true) do |f|
  p= f.label :name
  p= f.text_field :name
  p= f.submit

app/views/rooms/index.html.slim
h1 Rooms#index

ul
  - @rooms.each do |room|
    li = link_to room.name, room_path(room)

app/views/rooms/new.html.slim
h1 Rooms#new

= form_with(model: @room, local: true) do |f|
  p= f.label :name
  p= f.text_field :name
  p= f.submit

app/views/rooms/show.html.slim
h1 Rooms#show

#room_info
  | ルーム名
  = tag.span @room.name
  = link_to "変更", edit_room_path(@room)
  = link_to "削除", room_path(@room), method: :delete,
    data: { confirm: "このルームを削除しますか?" }

#new_post
  form
    label make a new post >&nbsp;
    = tag.input type: "text", id: "new_post_input",
      autocomplete: 'off', size: '30'
  hr

#room_posts
  == render @posts

== pagy_nav(@pagy)

#page-load-status
  p.infinite-scroll-request ※読み込み中※
  p.infinite-scroll-last ※これより古い投稿はありません※
  p.infinite-scroll-error ※読み込めません※

= javascript_include_tag "cable.js"
= javascript_include_tag "rooms.js"